[versions]

compose = "1.1.1"
androidx-lifecyle = "2.4.1"
material3 = "1.0.0-alpha02"
androidx-core = "1.7.0"
appcompat = "1.3.1"
espresso = "3.4.0"
junit = "4.13.2"
android-junit = "1.1.3"

[libraries]

# Implementations

androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecyle" }
androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "appcompat" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }

# Debug Implementations

compose-debug-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }

# Test Implementations

junit = { module = "junit:junit", version.ref = "junit" }

# Android Test Implementations

androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
android-junit = { module = "androidx.test.ext:junit", version.ref = "android-junit" }
compose-android-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }


[bundles]

androidx = [
    "androidx-core",
    "androidx-lifecycle"
]

androidx-test = [
    "androidx-espresso",
    "android-junit",
]

compose = [
    "compose-ui",
    "compose-tooling-preview",
]

compose-debug = [
    "compose-debug-tooling",
    "compose-test-manifest"
]

[plugins]