[versions]

kotlin = "1.6.10"
gradle = "7.3.0-alpha06"
compose = "1.1.1"
androidx-lifecyle = "2.4.1"
material3 = "1.0.0-alpha02"
coroutines = "1.3.9"
coroutines-android = "2.4.0"
androidx-core = "1.7.0"
splashscreen = "1.0.0-beta01"
appcompat = "1.3.1"
espresso = "3.4.0"
junit = "4.13.2"
android-junit = "1.1.3"
hilt = "2.28-alpha"
room = "2.4.2"
ksp = "1.6.10-1.0.2"
navigation = "2.4.1"

[libraries]

# Implementations

androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecyle" }
androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "appcompat" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "coroutines-android" }
coroutines-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "coroutines-android" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

room = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# Debug Implementations

compose-debug-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }

# Test Implementations

junit = { module = "junit:junit", version.ref = "junit" }

# Android Test Implementations

androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
android-junit = { module = "androidx.test.ext:junit", version.ref = "android-junit" }
compose-android-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

[bundles]

androidx = [
    "androidx-core",
    "androidx-lifecycle"
]

androidx-test = [
    "androidx-espresso",
    "android-junit",
]

coroutines = [
    "coroutines",
    "coroutines-viewmodel",
    "coroutines-lifecycle"
]

compose = [
    "compose-ui",
    "compose-tooling-preview",
    "compose-material3",
    "compose-runtime"
]

compose-debug = [
    "compose-debug-tooling",
    "compose-test-manifest"
]

[plugins]

android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "dagger.hilt.android.plugin" }