name: Android test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RELEASE_STORE_FILE: ${{ secrets.RELEASE_STORE_FILE }}
  RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
  RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
  RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Run unit test
        run: ./gradlew clean test

      - name: run android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          disable-animations: true
          force-avd-creation: false
          emulator-options: -no-snapshot -no-window -no-boot-anim -no-audio -camera-back none -camera-front none
          script: ./gradlew connectedAndroidTest
